import { Json } from "../database";
import { ThemeSettings } from "./theme";
import { NotificationPreferences } from "./notification";
import { CloudStorageSettings } from "./cloud-storage";

export interface UserSettingsTable {
  Row: {
    user_id: string;
    theme: "light" | "dark" | "system";
    language: "pt-BR" | "en-US";
    email_notifications: boolean;
    open_food_facts_api_key: string | null;
    google_calendar_connected: boolean;
    account_active: boolean;
    created_at: string;
    updated_at: string;
    auto_dark_mode: boolean;
    dark_mode_start: string;
    dark_mode_end: string;
    custom_theme: ThemeSettings;
    push_notifications: boolean;
    notification_preferences: NotificationPreferences;
    email_signature: string | null;
    email_filters: Json;
    auto_backup: boolean;
    backup_frequency: "daily" | "weekly" | "monthly";
    cloud_storage_provider: string | null;
    cloud_storage_settings: CloudStorageSettings | null;
    meal_delivery_connected: boolean;
    recipe_planning_connected: boolean;
    appointment_reminder_emails: boolean;
    progress_report_emails: boolean;
    newsletter_emails: boolean;
    email_frequency: "daily" | "weekly" | "monthly";
    appointment_reminder_template: string | null;
    progress_report_template: string | null;
    reschedule_template: string | null;
    cancellation_template: string | null;
    questionnaire_template: string | null;
    usda_fooddata_api_key: string | null;
    email_service: "resend" | "smtp";
    resend_api_key: string | null;
    smtp_host: string | null;
    smtp_port: string | null;
    smtp_user: string | null;
    smtp_password: string | null;
    smtp_secure: boolean;
    apple_health_connected: boolean;
    accessibility_settings: Json;
  };
  Insert: Omit<UserSettingsTable["Row"], "created_at" | "updated_at">;
  Update: Partial<UserSettingsTable["Insert"]>;
}