export interface AnamnesesTable {
  Row: {
    id: string;
    patient_id: string;
    nutritionist_id: string;
    anamnesis_date: string;
    chief_complaint: string | null;
    complaint_duration: string | null;
    previous_diseases: string | null;
    current_diseases: string | null;
    hospitalizations: string | null;
    surgeries: string | null;
    chronic_conditions: string | null;
    family_diseases: string | null;
    family_obesity: boolean | null;
    family_diabetes: boolean | null;
    family_hypertension: boolean | null;
    family_heart_disease: boolean | null;
    current_medications: string | null;
    vitamin_supplements: string | null;
    herbal_supplements: string | null;
    eating_pattern: string | null;
    food_allergies: string | null;
    food_intolerances: string | null;
    food_aversions: string | null;
    food_preferences: string | null;
    usual_breakfast: string | null;
    usual_lunch: string | null;
    usual_dinner: string | null;
    usual_snacks: string | null;
    water_intake_ml: number | null;
    alcohol_consumption: string | null;
    caffeine_intake: string | null;
    physical_activity_type: string | null;
    physical_activity_frequency: string | null;
    physical_activity_duration: string | null;
    smoking: boolean | null;
    smoking_details: string | null;
    sleep_hours: number | null;
    sleep_quality: string | null;
    stress_level: string | null;
    current_weight: number | null;
    height: number | null;
    bmi: number | null;
    waist_circumference: number | null;
    hip_circumference: number | null;
    body_fat_percentage: number | null;
    muscle_mass_percentage: number | null;
    constipation: boolean | null;
    diarrhea: boolean | null;
    bloating: boolean | null;
    heartburn: boolean | null;
    nausea: boolean | null;
    digestive_other: string | null;
    fatigue: boolean | null;
    headaches: boolean | null;
    mood_changes: boolean | null;
    skin_problems: boolean | null;
    hair_loss: boolean | null;
    other_symptoms: string | null;
    menstrual_cycle: string | null;
    pregnancy_history: string | null;
    lactation: boolean | null;
    weight_goal: string | null;
    primary_goals: string | null;
    expectations: string | null;
    motivation_level: string | null;
    barriers_to_change: string | null;
    recent_lab_results: string | null;
    lab_date: string | null;
    clinical_impression: string | null;
    nutritional_diagnosis: string | null;
    initial_recommendations: string | null;
    created_at: string;
    updated_at: string;
  };
  Insert: Omit<AnamnesesTable['Row'], 'id' | 'created_at' | 'updated_at'>;
  Update: Partial<AnamnesesTable['Insert']>;
}
