export interface PatientsTable {
  Row: {
    additional_notes: string | null;
    allergies: string | null;
    birth_date: string | null;
    blood_type: string | null;
    city: string | null;
    complement: string | null;
    cpf: string;
    created_at: string;
    current_weight: number | null;
    dietary_restrictions: string | null;
    email: string | null;
    exercise_duration: string | null;
    exercise_frequency: string | null;
    exercise_type: string | null;
    family_history: string | null;
    full_name: string;
    gender: string | null;
    height: number | null;
    id: string;
    meals_per_day: number | null;
    medical_conditions: string | null;
    medications: string | null;
    neighborhood: string | null;
    number: string | null;
    nutritional_goals: string | null;
    nutritionist_id: string | null;
    occupation: string | null;
    phone: string | null;
    postal_code: string | null;
    sleep_hours: number | null;
    sleep_quality: string | null;
    state: string | null;
    street: string | null;
    target_weight: number | null;
    treatment_expectations: string | null;
    updated_at: string;
  };
  Insert: {
    additional_notes?: string | null;
    allergies?: string | null;
    birth_date?: string | null;
    blood_type?: string | null;
    city?: string | null;
    complement?: string | null;
    cpf: string;
    created_at?: string;
    current_weight?: number | null;
    dietary_restrictions?: string | null;
    email?: string | null;
    exercise_duration?: string | null;
    exercise_frequency?: string | null;
    exercise_type?: string | null;
    family_history?: string | null;
    full_name: string;
    gender?: string | null;
    height?: number | null;
    id?: string;
    meals_per_day?: number | null;
    medical_conditions?: string | null;
    medications?: string | null;
    neighborhood?: string | null;
    number?: string | null;
    nutritional_goals?: string | null;
    nutritionist_id?: string | null;
    occupation?: string | null;
    phone?: string | null;
    postal_code?: string | null;
    sleep_hours?: number | null;
    sleep_quality?: string | null;
    state?: string | null;
    street?: string | null;
    target_weight?: number | null;
    treatment_expectations?: string | null;
    updated_at?: string;
  };
  Update: {
    additional_notes?: string | null;
    allergies?: string | null;
    birth_date?: string | null;
    blood_type?: string | null;
    city?: string | null;
    complement?: string | null;
    cpf?: string;
    created_at?: string;
    current_weight?: number | null;
    dietary_restrictions?: string | null;
    email?: string | null;
    exercise_duration?: string | null;
    exercise_frequency?: string | null;
    exercise_type?: string | null;
    family_history?: string | null;
    full_name?: string;
    gender?: string | null;
    height?: number | null;
    id?: string;
    meals_per_day?: number | null;
    medical_conditions?: string | null;
    medications?: string | null;
    neighborhood?: string | null;
    number?: string | null;
    nutritional_goals?: string | null;
    nutritionist_id?: string | null;
    occupation?: string | null;
    phone?: string | null;
    postal_code?: string | null;
    sleep_hours?: number | null;
    sleep_quality?: string | null;
    state?: string | null;
    street?: string | null;
    target_weight?: number | null;
    treatment_expectations?: string | null;
    updated_at?: string;
  };
  Relationships: [
    {
      foreignKeyName: "patients_nutritionist_id_fkey";
      columns: ["nutritionist_id"];
      isOneToOne: false;
      referencedRelation: "profiles";
      referencedColumns: ["id"];
    },
  ];
}
