// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rthwkkiddqvcignwrofj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0aHdra2lkZHF2Y2lnbndyb2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyOTUyNDUsImV4cCI6MjA0OTg3MTI0NX0.fI6a_W686gTIrQIrNiyHeFLl96TQK1LWjiCuiw0zEas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);